// ===========================
// Masar Platform — Mock Data (واقعية عربية)
// ===========================

import type {
  Student,
  University,
  Course,
  DegreeRequirement,
  Internship,
  Notification,
  TodayClass,
  Assignment,
} from "./types";

export const universities: University[] = [
  { id: "ju", name: "الجامعة الأردنية", nameEn: "University of Jordan" },
  { id: "just", name: "جامعة العلوم والتكنولوجيا الأردنية", nameEn: "JUST" },
  { id: "mut", name: "جامعة آل البيت", nameEn: "Al al-Bayt University" },
  { id: "ahu", name: "جامعة الحسين التقنية", nameEn: "Hussein Technical University" },
  { id: "gju", name: "الجامعة الألمانية الأردنية", nameEn: "German Jordanian University" },
  { id: "yu", name: "جامعة اليرموك", nameEn: "Yarmouk University" },
  { id: "bau", name: "جامعة البلقاء التطبيقية", nameEn: "Al-Balqa Applied University" },
  { id: "pu", name: "جامعة البترا", nameEn: "University of Petra" },
];

export const mockStudent: Student = {
  id: "s-001",
  name: "أحمد الخالدي",
  studentId: "2110456",
  email: "a.khalidi@students.ju.edu.jo",
  universityId: "ju",
  major: "هندسة الحاسوب",
  year: 3,
  gpa: 3.42,
  totalCredits: 136,
  completedCredits: 79,
  skills: ["Python", "Java", "React", "SQL", "Linux"],
  github: "github.com/ahmedkhalidi",
};

export const mockCourses: Course[] = [
  {
    id: "c-001",
    code: "CS301",
    nameAr: "هياكل البيانات",
    nameEn: "Data Structures",
    credits: 3,
    instructor: "د. محمد الشريف",
    room: "C2-304",
    color: "#6366F1",
    semester: "الفصل الثاني 2024-2025",
    status: "enrolled",
    schedule: [
      { day: "sun", startTime: "08:00", endTime: "09:30", type: "lecture" },
      { day: "tue", startTime: "08:00", endTime: "09:30", type: "lecture" },
      { day: "thu", startTime: "10:00", endTime: "12:00", type: "lab" },
    ],
    grade: { midterm: 38, assignments: 18, total: 56 },
    assignments: [
      {
        id: "a-001",
        courseId: "c-001",
        title: "تنفيذ شجرة AVL",
        dueDate: "2025-04-15",
        dueTime: "23:59",
        status: "pending",
        maxGrade: 20,
        type: "assignment",
      },
      {
        id: "a-002",
        courseId: "c-001",
        title: "مشروع الفصل — محرك بحث بسيط",
        dueDate: "2025-05-10",
        dueTime: "23:59",
        status: "pending",
        maxGrade: 30,
        type: "project",
      },
    ],
    files: [
      { id: "f-001", name: "محاضرة 1 — مقدمة", type: "pdf", url: "#", uploadedAt: "2025-02-10", week: 1 },
      { id: "f-002", name: "محاضرة 2 — القوائم المترابطة", type: "pdf", url: "#", uploadedAt: "2025-02-17", week: 2 },
      { id: "f-003", name: "محاضرة 3 — الأكوام والطوابير", type: "pdf", url: "#", uploadedAt: "2025-02-24", week: 3 },
      { id: "f-004", name: "Slides Week 4 — Trees", type: "pptx", url: "#", uploadedAt: "2025-03-03", week: 4 },
    ],
  },
  {
    id: "c-002",
    code: "CS315",
    nameAr: "قواعد البيانات 2",
    nameEn: "Database Systems II",
    credits: 3,
    instructor: "د. سلمى النابلسي",
    room: "B1-201",
    color: "#8B5CF6",
    semester: "الفصل الثاني 2024-2025",
    status: "enrolled",
    schedule: [
      { day: "mon", startTime: "10:00", endTime: "11:30", type: "lecture" },
      { day: "wed", startTime: "10:00", endTime: "11:30", type: "lecture" },
    ],
    grade: { midterm: 42, assignments: 20 },
    assignments: [
      {
        id: "a-003",
        courseId: "c-002",
        title: "تصميم قاعدة بيانات للمستشفى",
        dueDate: "2025-04-08",
        dueTime: "23:59",
        status: "submitted",
        maxGrade: 25,
        type: "project",
      },
    ],
    files: [
      { id: "f-005", name: "Lecture 1 — Normalization Review", type: "pdf", url: "#", uploadedAt: "2025-02-10", week: 1 },
      { id: "f-006", name: "Lecture 2 — Transactions", type: "pdf", url: "#", uploadedAt: "2025-02-17", week: 2 },
    ],
  },
  {
    id: "c-003",
    code: "CS320",
    nameAr: "شبكات الحاسوب",
    nameEn: "Computer Networks",
    credits: 3,
    instructor: "أ.د. خالد الرواشدة",
    room: "A3-102",
    color: "#06B6D4",
    semester: "الفصل الثاني 2024-2025",
    status: "enrolled",
    schedule: [
      { day: "sun", startTime: "11:00", endTime: "12:30", type: "lecture" },
      { day: "tue", startTime: "11:00", endTime: "12:30", type: "lecture" },
    ],
    grade: { midterm: 35 },
    assignments: [
      {
        id: "a-004",
        courseId: "c-003",
        title: "تقرير بروتوكول TCP/IP",
        dueDate: "2025-04-07",
        dueTime: "23:59",
        status: "pending",
        maxGrade: 15,
        type: "assignment",
      },
    ],
    files: [
      { id: "f-007", name: "Chapter 1 — Introduction", type: "pdf", url: "#", uploadedAt: "2025-02-10", week: 1 },
    ],
  },
  {
    id: "c-004",
    code: "MATH310",
    nameAr: "الاحتمالات والإحصاء",
    nameEn: "Probability & Statistics",
    credits: 3,
    instructor: "د. رنا عبيدات",
    room: "D1-401",
    color: "#F59E0B",
    semester: "الفصل الثاني 2024-2025",
    status: "enrolled",
    schedule: [
      { day: "mon", startTime: "12:00", endTime: "13:30", type: "lecture" },
      { day: "wed", startTime: "12:00", endTime: "13:30", type: "lecture" },
      { day: "thu", startTime: "14:00", endTime: "15:00", type: "tutorial" },
    ],
    assignments: [],
    files: [],
  },
  {
    id: "c-005",
    code: "CS330",
    nameAr: "هندسة البرمجيات",
    nameEn: "Software Engineering",
    credits: 3,
    instructor: "د. عمر حسين",
    room: "B2-305",
    color: "#10B981",
    semester: "الفصل الثاني 2024-2025",
    status: "enrolled",
    schedule: [
      { day: "tue", startTime: "14:00", endTime: "15:30", type: "lecture" },
      { day: "thu", startTime: "08:00", endTime: "09:30", type: "lecture" },
    ],
    grade: { midterm: 37, assignments: 22 },
    assignments: [
      {
        id: "a-005",
        courseId: "c-005",
        title: "مخطط UML للمشروع",
        dueDate: "2025-04-06",
        dueTime: "23:59",
        status: "pending",
        maxGrade: 20,
        type: "assignment",
      },
    ],
    files: [],
  },
];

export const mockTodayClasses: TodayClass[] = [
  {
    courseId: "c-001",
    courseCode: "CS301",
    courseNameAr: "هياكل البيانات",
    instructor: "د. محمد الشريف",
    room: "C2-304",
    startTime: "08:00",
    endTime: "09:30",
    type: "lecture",
    color: "#6366F1",
    status: "done",
  },
  {
    courseId: "c-003",
    courseCode: "CS320",
    courseNameAr: "شبكات الحاسوب",
    instructor: "أ.د. خالد الرواشدة",
    room: "A3-102",
    startTime: "11:00",
    endTime: "12:30",
    type: "lecture",
    color: "#06B6D4",
    status: "ongoing",
  },
  {
    courseId: "c-001",
    courseCode: "CS301",
    courseNameAr: "هياكل البيانات — مختبر",
    instructor: "م. ليلى مرعي",
    room: "Lab C-02",
    startTime: "14:00",
    endTime: "16:00",
    type: "lab",
    color: "#6366F1",
    status: "upcoming",
  },
];

export const mockDegreeRequirements: DegreeRequirement[] = [
  {
    id: "dr-001",
    category: "mandatory",
    categoryLabel: "متطلبات الكلية الإجبارية",
    totalCredits: 30,
    completedCredits: 21,
    courses: [
      { id: "dc-001", code: "CS101", nameAr: "مقدمة في علم الحاسوب", credits: 3, status: "completed", grade: "A" },
      { id: "dc-002", code: "CS102", nameAr: "البرمجة الهيكلية", credits: 3, status: "completed", grade: "B+" },
      { id: "dc-003", code: "CS201", nameAr: "البرمجة كائنية التوجه", credits: 3, status: "completed", grade: "A-" },
      { id: "dc-004", code: "CS210", nameAr: "المنطق الرياضي", credits: 3, status: "completed", grade: "B" },
      { id: "dc-005", code: "CS220", nameAr: "تصميم الدوائر الرقمية", credits: 3, status: "completed", grade: "B+" },
      { id: "dc-006", code: "CS230", nameAr: "نظرية الحساب", credits: 3, status: "completed", grade: "A" },
      { id: "dc-007", code: "CS240", nameAr: "نظم التشغيل", credits: 3, status: "completed", grade: "B" },
      { id: "dc-008", code: "CS301", nameAr: "هياكل البيانات", credits: 3, status: "enrolled" },
      { id: "dc-009", code: "CS315", nameAr: "قواعد البيانات 2", credits: 3, status: "enrolled" },
      { id: "dc-010", code: "CS410", nameAr: "الذكاء الاصطناعي", credits: 3, status: "available" },
    ],
  },
  {
    id: "dr-002",
    category: "major",
    categoryLabel: "متطلبات التخصص",
    totalCredits: 45,
    completedCredits: 24,
    courses: [
      { id: "dc-011", code: "CS320", nameAr: "شبكات الحاسوب", credits: 3, status: "enrolled" },
      { id: "dc-012", code: "CS330", nameAr: "هندسة البرمجيات", credits: 3, status: "enrolled" },
      { id: "dc-013", code: "CS350", nameAr: "الأمن المعلوماتي", credits: 3, status: "available" },
      { id: "dc-014", code: "CS360", nameAr: "الحوسبة السحابية", credits: 3, status: "locked" },
      { id: "dc-015", code: "CS490", nameAr: "مشروع التخرج", credits: 6, status: "locked" },
    ],
  },
  {
    id: "dr-003",
    category: "university",
    categoryLabel: "متطلبات الجامعة",
    totalCredits: 18,
    completedCredits: 15,
    courses: [
      { id: "dc-016", code: "AR101", nameAr: "اللغة العربية", credits: 3, status: "completed", grade: "A-" },
      { id: "dc-017", code: "EN101", nameAr: "اللغة الإنجليزية 1", credits: 3, status: "completed", grade: "B+" },
      { id: "dc-018", code: "EN102", nameAr: "اللغة الإنجليزية 2", credits: 3, status: "completed", grade: "B" },
      { id: "dc-019", code: "IS101", nameAr: "الثقافة الإسلامية", credits: 3, status: "completed", grade: "A" },
      { id: "dc-020", code: "MIL101", nameAr: "التربية العسكرية", credits: 3, status: "completed", grade: "A+" },
      { id: "dc-021", code: "MATH310", nameAr: "الاحتمالات والإحصاء", credits: 3, status: "enrolled" },
    ],
  },
  {
    id: "dr-004",
    category: "elective",
    categoryLabel: "مواد اختيارية",
    totalCredits: 12,
    completedCredits: 6,
    courses: [
      { id: "dc-022", code: "CS305", nameAr: "تطوير تطبيقات الويب", credits: 3, status: "completed", grade: "A" },
      { id: "dc-023", code: "CS306", nameAr: "تعلم الآلة", credits: 3, status: "completed", grade: "A-" },
      { id: "dc-024", code: "CS307", nameAr: "معالجة الصور", credits: 3, status: "available" },
      { id: "dc-025", code: "CS308", nameAr: "تطوير تطبيقات الجوال", credits: 3, status: "available" },
    ],
  },
];

export const mockInternships: Internship[] = [
  {
    id: "i-001",
    company: "زين الأردن",
    title: "متدرب — هندسة البرمجيات",
    location: "عمان، الأردن",
    type: "hybrid",
    duration: "3 أشهر",
    deadline: "2025-04-30",
    applyUrl: "https://zain.com/careers",
    tags: ["Backend", "Java", "Spring"],
    isNew: true,
  },
  {
    id: "i-002",
    company: "Extensya",
    title: "Junior Frontend Developer",
    location: "عمان، الأردن",
    type: "onsite",
    duration: "6 أشهر",
    deadline: "2025-05-15",
    applyUrl: "https://extensya.com/careers",
    tags: ["React", "TypeScript", "TailwindCSS"],
    isNew: true,
  },
  {
    id: "i-003",
    company: "Orange Jordan",
    title: "متدرب — أمن المعلومات",
    location: "عمان، الأردن",
    type: "onsite",
    duration: "3 أشهر",
    deadline: "2025-04-20",
    applyUrl: "https://orange.jo/careers",
    tags: ["Cybersecurity", "Linux", "Networking"],
  },
  {
    id: "i-004",
    company: "Edraak",
    title: "Data Science Intern",
    location: "Remote",
    type: "remote",
    duration: "4 أشهر",
    deadline: "2025-06-01",
    applyUrl: "https://edraak.org/careers",
    tags: ["Python", "Data Analysis", "ML"],
  },
  {
    id: "i-005",
    company: "Aramex",
    title: "متدرب — تكنولوجيا المعلومات",
    location: "عمان، الأردن",
    type: "onsite",
    duration: "3 أشهر",
    applyUrl: "https://aramex.com/careers",
    tags: ["Networking", "IT Support", "Cloud"],
  },
  {
    id: "i-006",
    company: "Luminus Technical University College",
    title: "مساعد بحثي — تعلم الآلة",
    location: "عمان، الأردن",
    type: "hybrid",
    duration: "6 أشهر",
    deadline: "2025-05-30",
    applyUrl: "#",
    tags: ["AI", "Python", "Research"],
    isNew: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n-001",
    type: "deadline",
    title: "تسليم قريب — هندسة البرمجيات",
    body: "مخطط UML للمشروع — يُسلَّم خلال ساعات",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    read: false,
    link: "/courses/c-005",
  },
  {
    id: "n-002",
    type: "deadline",
    title: "تسليم خلال 24 ساعة — شبكات الحاسوب",
    body: "تقرير بروتوكول TCP/IP",
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    read: false,
    link: "/courses/c-003",
  },
  {
    id: "n-003",
    type: "grade",
    title: "ظهرت درجة جديدة",
    body: "درجة الامتحان النصفي — قواعد البيانات 2: 42/50",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    read: true,
    link: "/courses/c-002",
  },
];

export const urgentAssignments: Assignment[] = mockCourses
  .flatMap((c) => c.assignments)
  .filter((a) => a.status === "pending")
  .slice(0, 3);
